### ISSUE TITLE
Configurable yell() and say() prefix 

### ISSUE THREAD

**Issue by Sweetchuck** [consolidation-org/Robo#354]
The prefix of the `\Robo\Common\IO::say()` and `::yell()` is hard-coded to `$char = strncasecmp(PHP_OS, 'WIN', 3) == 0 ? '>' : '➜';` and two spaces.
This means that if somebody wants to write Behat test for an application which uses Robo in the background then impossible to write step definition for all platform.
For example

```cucumber
Then I should see the following text in the output:
"""
➜  Line 1
➜  Line 2
"""
```

It would be awesome if the prefix were configurable. (or same on all platform)

**Comment by greg-1-anderson** [comment]
Submitted a proposed solution in #355. With this PR, you could call `Config::setYellPrefix()` in your test initialization to set this to a constant value.

**Comment by DavertMik** [comment]
`Config::setYellPrefix()` 
I think we will end up with filling Config class with lots of static methods for basic config changes. I think we can use `--no-ansi` option from Symfony console which disables non-ansi output. In our case it can also replace UTF chars to basic ANSI output.

**Comment by greg-1-anderson** [comment]
That's a good idea.
