### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by greg-1-anderson** [consolidation-org/Robo#356]
* [ ] Add [Add your tasks] to Tasks menu. Write a guide on how to create 3rd party tasks, include them and register them inside container.
* [ ] Show how folks can include Robo in their composer.json, and make a Symfony/Console commandline tool very quickly, and also leverage Robo tasks from their commands.
* [ ] Update for using Result object
* [ ] Customization guide:
  - using container
  - adding logger
  - changing output 
  - events?

**Comment by reconstrukt** [comment]
also! for windows users, show how to use robo via cli/powershell

**Comment by DavertMik** [comment]
> Show how folks can include Robo in their composer.json, and make a Symfony/Console commandline tool very quickly, and also leverage Robo tasks from their commands.

I think we should mention that Robo can be a framework for building CLI applications. And probably a special page for that. Do you have example of such application?

**Comment by DavertMik** [comment]
> Add [Add your tasks] to Tasks menu. Write a guide on how to create 3rd party tasks, include them and register them inside container.

I can do that. In branch `site` there is `mkdocs.yml` which you can edit to add more menu items

**Comment by greg-1-anderson** [comment]
> Do you have example of such application?

[Drush](https://github.com/drush-ops/drush/blob/master/composer.json#L37)!

**Comment by DavertMik** [comment]
Yes, could you transform that experience in a guide page like `docs/framework.md` ?

**Comment by DavertMik** [comment]
You can also include all the customization stuff you mentioned here into it

**Comment by greg-1-anderson** [comment]
Working on this in #415.
