### ISSUE TITLE
Ensure that the execution time of tasks is uniformly available in $result

### ISSUE THREAD

**Issue by vitalyspirin** [consolidation-org/Robo#368]
After I execute command (Ssh::run()) I get back Result object. The time fields are inside Result->getTask() but then I can't run getExecutionTime() because it's protected.

**Comment by greg-1-anderson** [comment]
Clients should depend on `$result['time']` rather than inspecting the task object.  We should ensure that this field is populated consistently in all non-trivial built-in tasks.

**Comment by DavertMik** [comment]
Yes. This should be part of `Result` object. Should we add a method `getTime` to it?

**Comment by greg-1-anderson** [comment]
Yes, good idea; I'll add that.

If a command does not know how long it took to execute, should `getTime()` just return 0?

**Comment by greg-1-anderson** [comment]
Another thing we could do to increase standardization here is to make `BaseTask::run()` start the timer, then call `BaseTask::do()`, and then stop the timer (and add the time to the Result returned by `do()`).

This would mean that all tasks that extended BaseTask would implement `do()` instead of `run()`.  This is a pretty sweeping change; however, it isn't really a b/c break, because tasks that continued to use `run()` would still work, they just wouldn't get timing info (unless they explicitly add it, like today).

**Comment by royallthefourth** [comment]
Returning zero would mislead users into thinking their tasks had run much quicker than they actually had. It might be better to throw an exception instead to make it clear what's actually happening.

**Comment by greg-1-anderson** [comment]
Robo tends to not throw exceptions, but in this case I think it's warranted.  Perhaps include a `hasTime()` method, in case someone wants to inspect the result of a Result from an unknown task.

**Comment by DavertMik** [comment]
> This would mean that all tasks that extended BaseTask would implement do() instead of run(). This is a pretty sweeping change; however, it isn't really a b/c break, because tasks that continued to use run() would still work, they just wouldn't get timing info (unless they explicitly add it, like today).

No, too much efforts for nothing. Manual timer is ok. 

> Returning zero would mislead users into thinking their tasks had run much quicker than they actually had. It might be better to throw an exception instead to make it clear what's actually happening.

Or just to return `null`. That will be correct.

**Comment by greg-1-anderson** [comment]
#397

**Comment by greg-1-anderson** [comment]
Fixed in #397.  As long as clients are using a collection builder, they will have access to `$result['time']`
