### ISSUE TITLE
How Can I read the taskExec output ?

### ISSUE THREAD

**Issue by borgogelli** [consolidation-org/Robo#382]
Hi

some task, call a system command which produces some outputs.
Robo can prints out them on video but how can I store it in a var ?

For example
```
 $result = $this->taskExec('java -jar ' . $my_jar)
        ->background()
        ->run();
```
Can I extract the command output from the $result object ?

Thank you

Andrea

**Comment by Sweetchuck** [comment]
I think the `$result->getMessage()` will be you friend.

https://github.com/consolidation-org/Robo/blob/ff86b2cb870424dfdfd347cd2b7e180a2647ddd0/src/Task/Base/Exec.php#L154

**Comment by borgogelli** [comment]
Hi Sweetchuck ,
getMessage() sometimes returns an empty string like in following snippet:

`$result = $this->svnExec(realpath($dir, "info");`

**Comment by Sweetchuck** [comment]
It gives a different result on success and on fail.
https://github.com/consolidation-org/Robo/blob/141bc9976e73201b93e9ee07c950951f239b278b/src/Task/CommandStack.php#L65

On success there is no information about the StdOut

**Comment by borgogelli** [comment]
Well, so how can I read the StdOut when task end successfully ? See the above example, where I'd like to read the output of the "svn info" command. I know that a task has a logger object linked. Could it be useful to read the StdOut ?

**Comment by greg-1-anderson** [comment]
Do you need access to stdout for tasks that perform an operation?

In your first example, you are using `->background()` to run a Java server in the background.  A Robo execTask is not a good way to monitor the output from a long-running background task.  Use a log file, or run the process via the Symfony process component directly.

In the second example, a Robo taskExec is not a good way to obtain information about the system, e.g. when building your task objects.  Instead, you should use the php `exec` function, or the Symfony Process component to call things such as `svn info`.

Use taskExec for commands that change the state of the system.  When implementing a task that needs to `exec` a tool, then it is preferable to `use ExecCommand` or extend your class from `CommandStack`.

**Comment by borgogelli** [comment]
Thanks a lot Greg for clearing up the usage of "taskExec". 
The confusion arises from the following example in the getting-start guide:
` $this->taskExec ('ls')->args($args )->run() ;` (here I get information and I don't change the state of the system)
I think that your clarification will also be useful to other users .
Regards from Italy

**Comment by borgogelli** [comment]
Thanks

**Comment by greg-1-anderson** [comment]
Good point -- we should change that example.

**Comment by geek-merlin** [comment]
I had that problem with current robo / openeuropa/task-runner, and the search engine directed me here.

What made me succeed was `->printOutput(false)`like so:
```
    $hash = $this->taskExec('git rev-parse HEAD')
      ->printOutput(false)
      ->run()->stopOnFail()->getMessage();
```

**Comment by dgrothaus-mc** [comment]
> ```
>     $hash = $this->taskExec('git rev-parse HEAD')
>       ->printOutput(false)
>       ->run()->stopOnFail()->getMessage();
> ```

You are the MVP. That helped a lot. Thank you.
