### ISSUE TITLE
Collection has inconsistent return value

### ISSUE THREAD

**Issue by Sweetchuck** [consolidation-org/Robo#385]
When a `\Robo\Collection\Collection::run()` triggered then the type of the return value depends on the outcome.
If it failed it returns a `\Robo\ResultData` otherwise it returns a `\Robo\Result` (or other way around)

I would like to write a code like this, but it does not work in both cases, because `\Robo\ResultData` has no `::stopOnFail()` method.
``` php
<?php
$collection
  ->add(/* Foo */)
  ->run()
  ->stopOnFail()
```

**Comment by greg-1-anderson** [comment]
In general, you shouldn't use stopOnFail with collections.

The trouble with ResultData vs. Result is that a Result must contain a task, but that is not available in all contexts.  This should be better.  Suggestions / PRs on suggested ways to improve this situation are appreciated.

**Comment by greg-1-anderson** [comment]
c.f. #381

**Comment by greg-1-anderson** [comment]
Try again on the HEAD of master.  All tasks (including collections) should now always return Result objects.  ResultData is still available, but should only be used in RoboFile commands in instances where there is no task.  (Rare: see the `try:formatters` command.)

`stopOnFail` is still supported for all Result objects, including those returned from Collections.  I would still recommend avoiding using `stopOnFail` with Collections, though, as it should usually be unnecessary to do so.

**Comment by Sweetchuck** [comment]
Thank you. I will try it (probably at weekend).
I work on this: https://github.com/Cheppers/robo-phpcs
