### ISSUE TITLE
Collection is not Collectable

### ISSUE THREAD

**Issue by Sweetchuck** [consolidation-org/Robo#386]
Actually a collection can contains other collection as well as normal tasks. But nothings implies that it is possible.

A `$collection` has no for example `::addToCollection()` method. Which in case of the `\Robo\Task\BaseTask` comes from the `\Robo\Collection\Collectable` trait.

So I can't write a code like this:
```php
$collection_main = $this->collection();
$this->collection()
  ->add(/* foo */)
  ->addToCollection($collection_main);
```

But this one works:
```php
$collection_main = $this->collection();
$collection_child = $this->collection();
$collection_child->add(/* foo*/)
$collection_main->add($collection_child);
```

1. A some kind of `CollectableInterface` would be awesome
1. and/or it could be part of the `TaskInterface`
1. I haven't found `CollectionInterface` yet, but if it exists then it should implement the `CollectableInterface`

**Comment by greg-1-anderson** [comment]
Actually, I am planning on removing collectable in favor of the new collection builder class.  Please check out HEAD of master, and read the new docs/collections.md.  Feedback appreciated.

**Comment by greg-1-anderson** [comment]
See #393

**Comment by greg-1-anderson** [comment]
#393 will be merged, so Collectable will go away.  However, it is possible with the new builder to nest collections.  Comment on the referenced PR or forever hold your peace. 😄
