### ISSUE TITLE
Clean up Robo globals

### ISSUE THREAD

**Issue by greg-1-anderson** [consolidation-org/Robo#387]
Folks in #383 want more control over how Robo does output. I think there are better ways to do this than add more globals.  Before I document this, though, I'd like to do some cleanup.

As a general rule, an application's data objects should not keep references to the container -- or to other objects that keep references to the container. To keep Robo clean in this respect, I would like to split out a `Robo` class from the existing `Config` class.  The static Robo class would contain the reference to the container, and all related things, like the `input()` and `output()` methods.  `Config`, then, would keep only configuration values, not service references.  This change would affect everyone who calls `Config::getContainer()` or `Config::output()`; however, this practice is deprecated anyway, so I don't feel bad about forcing folks who do this to change to `Robo::getContainer()`.  (n.b. we can name this new static class anything.)

Once we do this, then `Config` will be free of container references. We can remove the static from ContainerBuilder, and replace it with a reference to Config via ConfigAwareInterface / Trait.

After that, we could consider giving RoboFiles an init method, and hand them the container; then they would be able to replace ResultPrinter or the logger or whatever they want to do if they don't like the default printing options.

**Comment by DavertMik** [comment]
> After that, we could consider giving RoboFiles an init method, and hand them the container; then they would be able to replace ResultPrinter or the logger or whatever they want to do if they don't like the default printing options.

Sorry, I didn't understand the implementation part but I really like this idea of providing `init` method for reconfiguring container. If you feel this is the reasonable way, please proceed.

**Comment by greg-1-anderson** [comment]
I'm ambivalent about what to do via-a-vis output control, but I want to avoid statics and globals. I'll do the refactor suggested above, and then add a proposal for container manipulation as a follow-on issue.

**Comment by Sweetchuck** [comment]
Will be there interfaces for every task?
It isn't sure what I take out from the container it is instance of a certain class, but it has to implement a certain interface.

**Comment by greg-1-anderson** [comment]
There is no proposal at the moment, but if we did go with container manipulation, we would need to add an interface for ResultPrinter; folks would then replace the 'resultPrinter' in the container with their own implementation.

Tasks already have an interface, `TaskInterface`. n.b. Tasks can also implement `PrintedInterface`, which allows them to control whether or not the `message` of a Result is printed during error handling.  However, the use-case under discussion at this time is how Robo commands can affect the behavior of the tasks that they run, e.g. to suppress task progress output.

**Comment by borgogelli** [comment]
As you told, I have switched from `Robo\Config::getContainer();` to `Robo\Robo::getContainer();`
With robo 1.05 I get the following error:
`Fatal error: Uncaught exception 'RuntimeException' with message 'container is not initialized yet. Robo\Robo::setContainer() must be called with a real container.' `

**Comment by greg-1-anderson** [comment]
@borgogelli You should open a separate issue for support requests, and provide more information about what you are trying to do.

The error message you are getting indicates that you have not initialized Robo in your application. You should follow the setup instructions described in [Robo as a Framework](http://robo.li/framework/).

**Comment by borgogelli** [comment]
Thank you Greg. I have opened the new issue #501
