### ISSUE TITLE
Laravel

### ISSUE THREAD

**Issue by rogoit** [consolidation-org/Robo#406]
Hi,

it is not working with laravel. Problem is the symfony-dispatcher.
- Installation request for codegyre/robo ^0.7.2 -> satisfiable by codegyre/robo[0.7.2].
- Conclusion: remove symfony/event-dispatcher v3.1.3
- Conclusion: don't install symfony/event-dispatcher v3.1.3

See you
Roland

**Comment by greg-1-anderson** [comment]
Try the latest version of Robo.  This seems to work for me:
```
composer require consolidation/Robo:1.0.0-beta1 laravel/installer
```
I did not attempt to use Robo and Laravel together, but I could run `laravel new` after the above command completed.

If you are looking to do a global install of Robo &/or Laravel, please see [cgr](https://github.com/consolidation-org/cgr).
