### ISSUE TITLE
Consider further adjustments to Robo's chdir behavior

### ISSUE THREAD

**Issue by greg-1-anderson** [consolidation-org/Robo#413]
Low-priority continuation of #409.

I fixed that PR as we discussed, moving the chdir into the --load-from code. This fixes my primary use-case, which is that it is now possible to make a standalone phar based on Robo that does not chdir.  This makes it possible to implement “ls” in Robo, to give a trivial example.

However, with this implementation, it still is not inconvenient to do the same thing via a bash alias that uses --load-from.  For example, you could not do:

`alias myls='robo --load-from=/path/to/my/RoboFile.php myls'`

If you tried this, you would find the cwd was always in the same directory as the RoboFile. You could recover the cwd via `getenv("PWD")` on Mac and Linux, but I'm not sure if that works the same way on Windows.

I tend to think that having the cwd remain unchanged is more useful than having it move to be relative to the RoboFile, as you have __DIR__ in the RoboFile if you'd like to load assets stored next to your code.  Also, I did consider submitting a PR that allowed the behavior of this to be selected via an option, but accessing options isn't really convenient in this part of the code.

If you still feel the same way about this (current behavior should be maintained), then go ahead and close this issue, as it's not super important to me.  I do kinda think it should go the other way, though.

**Comment by DavertMik** [comment]
Yeah, I think this a rare case. For most things people writing tasks expect them to be executed in the same dir as Robofile is no matter where they executed them. They won't start thinking in terns of using DIR just for the sake of better flexibility. So yes, I'd like to keep current behavior as it is easier for use. If anyone needs something better they can extend Robo or built their own app on top of it
