### ISSUE TITLE
$timer property defined in several Traits

### ISSUE THREAD

**Issue by amirduran** [consolidation-org/Robo#419]
It seems that Archive package is having problems with $timer property being defined in multiple files. 

Here is an error that I get: 

Robo\Task\BaseTask and Robo\Common\Timer define the same property ($timer) in the composition of Robo\Task\Archive\Pack. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed
in phar:///release/robo/robo.phar/src/Task/Archive/Pack.php:232

**Comment by greg-1-anderson** [comment]
Can't reproduce the symptom with php 7.0, 5.6 or 5.5, but I do see that the code is as you describe.

What version of PHP are you using?

**Comment by greg-1-anderson** [comment]
I removed the no-longer-necessary `use` statements, even though I could not reproduce this.
