### ISSUE TITLE
Error with printTaskInfo in a task

### ISSUE THREAD

**Issue by oscarotero** [consolidation-org/Robo#421]
Hello
I'm using the v1.0.0-RC and getting the following error with [GettextRobo](https://github.com/oscarotero/GettextRobo) task:
```
ERROR: Uncaught Error: Call to a member function isSupressed() on null in /Users/oscarotero/www/vendor/consolidation/robo/src/Common/TaskIO.php:110
Stack trace:
#0 /Users/oscarotero/www/vendor/consolidation/robo/src/Common/TaskIO.php(57): Robo\Task\BaseTask->printTaskOutput('notice', 'Gettext exporte...', Array)
#1 /Users/oscarotero/www/vendor/gettext/robo/src/GettextScanner.php(116): Robo\Task\BaseTask->printTaskInfo('Gettext exporte...')
#2 /Users/oscarotero/www/RoboFile.php(49): Gettext\Robo\TaskGettextScanner->run()
#3 [internal function]: RoboFile->gettext(Array)
#4 /Users/oscarotero/www/vendor/consolidation/annotated-command/src/CommandProcessor.php(132): call_user_func_array(Array, Array)
#5 /Users/oscarotero/www/vendor/consolidation/annotated-command/src/CommandProcessor.php(93): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Array)
#6 /Users/oscarotero/www/vendor/consolidation/annotated-command/src/CommandProcessor.php(65):
in /Users/oscarotero/www/vendor/consolidation/robo/src/Common/TaskIO.php:110
```
Not sure whether some BC changes requires to fix the Gettext task to be compatible with this new version.

**Comment by greg-1-anderson** [comment]
This particular error is fixed in the `dev-master` branch of Robo, and will be in 1.0.0-RC2, which will be tagged shortly.

However, this is a symptom that the Robo extension you are using was written for an earlier version of Robo, and must be updated for verison 1.0.0, which is not fully backwards-compatible with 0.6.0.  Please see the CHANGELOG file for details.

**Comment by oscarotero** [comment]
Hello. Thanks for you response.
I'm the creator of GettextRobo extension and am happy to make the changes to be compatible with the new 1.x version.
As I can see in the docs, the main difference with the 0.x, is the use of `$this->task()` to create task instances. So I've made this commit: https://github.com/oscarotero/GettextRobo/commit/f2260a8bacc62de980a62bef4d4741dbf887d61e and with robo `dev-master` now works fine.

**Comment by greg-1-anderson** [comment]
Great -- thanks for upgrading!

**Comment by greg-1-anderson** [comment]
Robo 1.0.0 stable should be tagged shortly.
