### ISSUE TITLE
Error trying to use Pass-Through Arguments

### ISSUE THREAD

**Issue by xelber** [consolidation-org/Robo#423]
As one of the sample suggest, ran the following
function ls($args)
    {
        $this->taskExec('ls')->args($args)->run();
    }

with robo ls -- Robo -c --all
Gives me 
 [RuntimeException]
  Not enough arguments (missing: "args").

**Comment by greg-1-anderson** [comment]
See `http://robo.li/getting-started/`: you need to typehing $args as `array $args` to signal Robo that your last argument takes a variable number of arguments.  You **must** use variable number of arguments in order to use pass-through args in Robo 1.x.

To test:
```
./robo try:array-args a b c -- -1 -2 -3
```
